/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/vin/{vin}/decode": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Decode a VIN */
        get: operations["decodeVin"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vehicles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List vehicles */
        get: operations["listVehicles"];
        put?: never;
        /** Create a vehicle */
        post: operations["createVehicle"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vehicles/{vehicleId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a vehicle */
        get: operations["getVehicle"];
        put?: never;
        post?: never;
        /** Soft-delete a vehicle */
        delete: operations["deleteVehicle"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vehicles/{vehicleId}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change vehicle status */
        post: operations["changeVehicleStatus"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vehicles/{vehicleId}/price": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change an asking price */
        post: operations["changeVehiclePrice"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vehicles/{vehicleId}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Publish to the website and syndication channels */
        post: operations["publishVehicle"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ChangePriceRequest: {
            priceType: string;
            newPrice: string;
            reason: string | null;
        };
        ChangeStatusRequest: {
            status: string;
            reason: string | null;
        };
        CreateVehicleCommand: {
            stockNumber?: string | null;
            vin?: string | null;
            decodeVin?: boolean;
            /** Format: int32 */
            modelYear?: number | null;
            make?: string | null;
            model?: string | null;
            trim?: string | null;
            /** Format: int32 */
            mileage?: number | null;
            exteriorColor?: string | null;
            interiorColor?: string | null;
            listPrice?: string | null;
            location?: string | null;
            notes?: string | null;
        };
        PagedResultOfVehicleSummaryDto: {
            items: components["schemas"]["VehicleSummaryDto"][];
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            pageSize: number;
            /** Format: int32 */
            totalCount: number;
            /** Format: int32 */
            totalPages?: number;
        };
        ProblemDetails: {
            type?: string | null;
            title?: string | null;
            /** Format: int32 */
            status?: number | null;
            detail?: string | null;
            instance?: string | null;
        };
        PublishReadinessDto: {
            /** Format: int32 */
            satisfied: number;
            /** Format: int32 */
            total: number;
            missing: string[];
        };
        VehicleDto: {
            /** Format: uuid */
            id: string;
            stockNumber: string;
            vin: string | null;
            /** Format: int32 */
            modelYear: number | null;
            make: string | null;
            model: string | null;
            trim: string | null;
            bodyStyle: string | null;
            driveType: string | null;
            engine: string | null;
            fuelType: string | null;
            transmission: string | null;
            exteriorColor: string | null;
            interiorColor: string | null;
            /** Format: int32 */
            mileage: number | null;
            status: string;
            listPrice: string | null;
            description: string | null;
            aiDescriptionDraft: string | null;
            /** Format: date */
            acquiredAt: string | null;
            /** Format: date */
            availableAt: string | null;
            /** Format: date */
            soldAt: string | null;
            isPublished: boolean;
            location: string | null;
            notes: string | null;
            /** Format: int32 */
            daysInInventory: number | null;
            readiness: components["schemas"]["PublishReadinessDto"];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        VehicleSummaryDto: {
            /** Format: uuid */
            id: string;
            stockNumber: string;
            vin: string | null;
            /** Format: int32 */
            modelYear: number | null;
            make: string | null;
            model: string | null;
            trim: string | null;
            /** Format: int32 */
            mileage: number | null;
            exteriorColor: string | null;
            status: string;
            listPrice: string | null;
            /** Format: int32 */
            daysInInventory: number | null;
            /** Format: int32 */
            daysToSale: number | null;
            isPublished: boolean;
            /** Format: int32 */
            photoCount: number;
        };
        VinDecodeDto: {
            vin: string;
            provider: string;
            fromCache: boolean;
            checkDigitValid: boolean;
            /** Format: int32 */
            modelYear: number | null;
            make: string | null;
            model: string | null;
            trim: string | null;
            bodyStyle: string | null;
            driveType: string | null;
            engine: string | null;
            fuelType: string | null;
            transmission: string | null;
            manufacturer: string | null;
            errorText: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    decodeVin: {
        parameters: {
            query?: {
                refresh?: boolean;
            };
            header?: never;
            path: {
                vin: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VinDecodeDto"];
                };
            };
            /** @description Missing, expired, or invalid credentials. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                };
            };
            /** @description The principal lacks the required permission. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                };
            };
            /** @description Not found, or the resource belongs to another tenant. These cases are deliberately indistinguishable: a 403 would confirm the record exists. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    listVehicles: {
        parameters: {
            query?: {
                page?: number;
                pageSize?: number;
                sort?: string;
                q?: string;
                status?: string[];
                make?: string;
                model?: string;
                isPublished?: boolean;
                ageDaysMin?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedResultOfVehicleSummaryDto"];
                };
            };
            /** @description Missing, expired, or invalid credentials. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                };
            };
            /** @description The principal lacks the required permission. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                };
            };
        };
    };
    createVehicle: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateVehicleCommand"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VehicleDto"];
                };
            };
            /** @description Missing, expired, or invalid credentials. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                };
            };
            /** @description The principal lacks the required permission. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    getVehicle: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vehicleId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VehicleDto"];
                };
            };
            /** @description Missing, expired, or invalid credentials. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                };
            };
            /** @description The principal lacks the required permission. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                };
            };
            /** @description Not found, or the resource belongs to another tenant. These cases are deliberately indistinguishable: a 403 would confirm the record exists. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                };
            };
        };
    };
    deleteVehicle: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vehicleId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing, expired, or invalid credentials. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                };
            };
            /** @description The principal lacks the required permission. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                };
            };
            /** @description Not found, or the resource belongs to another tenant. These cases are deliberately indistinguishable: a 403 would confirm the record exists. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    changeVehicleStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vehicleId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangeStatusRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VehicleDto"];
                };
            };
            /** @description Missing, expired, or invalid credentials. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                };
            };
            /** @description The principal lacks the required permission. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                };
            };
            /** @description Not found, or the resource belongs to another tenant. These cases are deliberately indistinguishable: a 403 would confirm the record exists. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    changeVehiclePrice: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vehicleId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePriceRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VehicleDto"];
                };
            };
            /** @description Missing, expired, or invalid credentials. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                };
            };
            /** @description The principal lacks the required permission. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                };
            };
            /** @description Not found, or the resource belongs to another tenant. These cases are deliberately indistinguishable: a 403 would confirm the record exists. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    publishVehicle: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vehicleId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VehicleDto"];
                };
            };
            /** @description Missing, expired, or invalid credentials. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                };
            };
            /** @description The principal lacks the required permission. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                };
            };
            /** @description Not found, or the resource belongs to another tenant. These cases are deliberately indistinguishable: a 403 would confirm the record exists. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
}
