/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/vin/{vin}/decode": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Decode a VIN */
        get: operations["decodeVin"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Authenticate with email and password
         * @description Returns tokens only when no second factor is outstanding. Because MFA is mandatory, the normal responses are mfaRequired or mfaEnrolmentRequired. The response for an unknown address is identical to the response for a wrong password, and the timing is equalised, so this endpoint cannot be used to discover which addresses have accounts.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/mfa/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Complete authentication with a TOTP code */
        post: operations["verifyMfa"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/mfa/enrol": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm a new authenticator and finish signing in */
        post: operations["confirmMfaEnrolment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/mfa/recovery": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Complete authentication with a single-use recovery code
         * @description For a user who has lost access to their authenticator. It is a second factor, not a bypass: the challenge token from the password step is still required, each code works exactly once, and a wrong code counts toward lockout exactly as a wrong TOTP code does.
         */
        post: operations["redeemRecoveryCode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/mfa/recovery-codes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** How many recovery codes remain unused */
        get: operations["getRecoveryCodeStatus"];
        put?: never;
        /**
         * Issue a fresh set of recovery codes, discarding the old ones
         * @description The codes are returned in plaintext exactly once. They are stored hashed, so a user who loses them has to generate a new set rather than retrieve the old one.
         */
        post: operations["regenerateRecoveryCodes"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Exchange a refresh token for a new pair
         * @description Refresh tokens rotate on every use. Presenting a token that has already been rotated is treated as evidence of theft: the entire token family is revoked and a fresh sign-in is required.
         */
        post: operations["refreshToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke the current session */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The authenticated principal, tenant, and effective permissions */
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vehicles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List vehicles */
        get: operations["listVehicles"];
        put?: never;
        /** Create a vehicle */
        post: operations["createVehicle"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vehicles/{vehicleId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a vehicle */
        get: operations["getVehicle"];
        put?: never;
        post?: never;
        /** Soft-delete a vehicle */
        delete: operations["deleteVehicle"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vehicles/{vehicleId}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change vehicle status */
        post: operations["changeVehicleStatus"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vehicles/{vehicleId}/price": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change an asking price */
        post: operations["changeVehiclePrice"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vehicles/{vehicleId}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Publish to the website and syndication channels */
        post: operations["publishVehicle"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AuthResponse: {
            outcome: string;
            tokens: components["schemas"]["TokenPair"];
            challengeToken: string | null;
            enrolmentSecret: string | null;
            enrolmentUri: string | null;
            recoveryCodes: string[] | null;
        };
        ChangePriceRequest: {
            priceType: string;
            newPrice: string;
            reason: string | null;
        };
        ChangeStatusRequest: {
            status: string;
            reason: string | null;
        };
        CreateVehicleCommand: {
            stockNumber?: string | null;
            vin?: string | null;
            decodeVin?: boolean;
            /** Format: int32 */
            modelYear?: number | null;
            make?: string | null;
            model?: string | null;
            trim?: string | null;
            /** Format: int32 */
            mileage?: number | null;
            exteriorColor?: string | null;
            interiorColor?: string | null;
            listPrice?: string | null;
            location?: string | null;
            notes?: string | null;
        };
        CurrentUserDto: {
            /** Format: uuid */
            id: string;
            email: string;
            firstName: string;
            lastName: string;
            displayName: string;
            tenant: components["schemas"]["TenantDto"];
            roles: string[];
            permissions: string[];
            mfaEnrolled: boolean;
        };
        LoginRequest: {
            email: string | null;
            password: string | null;
        };
        PagedResultOfVehicleSummaryDto: {
            items: components["schemas"]["VehicleSummaryDto"][];
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            pageSize: number;
            /** Format: int32 */
            totalCount: number;
            /** Format: int32 */
            totalPages?: number;
        };
        ProblemDetails: {
            type?: string | null;
            title?: string | null;
            /** Format: int32 */
            status?: number | null;
            detail?: string | null;
            instance?: string | null;
        };
        PublishReadinessDto: {
            /** Format: int32 */
            satisfied: number;
            /** Format: int32 */
            total: number;
            missing: string[];
        };
        RecoveryCodeSetDto: {
            codes: string[];
            /** Format: date-time */
            issuedAt: string;
        };
        RecoveryCodeStatusDto: {
            /** Format: int32 */
            remaining: number;
            /** Format: int32 */
            setSize: number;
        };
        RedeemRecoveryCodeRequest: {
            challengeToken: string | null;
            code: string | null;
        };
        RefreshRequest: {
            refreshToken: string | null;
        };
        TenantDto: {
            /** Format: uuid */
            id: string;
            slug: string;
            legalName: string;
            stateCode: string | null;
        };
        TokenPair: {
            accessToken: string;
            refreshToken: string;
            tokenType: string;
            /** Format: int32 */
            expiresIn: number;
        } | null;
        TokenPair2: {
            accessToken: string;
            refreshToken: string;
            tokenType: string;
            /** Format: int32 */
            expiresIn: number;
        };
        VehicleDto: {
            /** Format: uuid */
            id: string;
            stockNumber: string;
            vin: string | null;
            /** Format: int32 */
            modelYear: number | null;
            make: string | null;
            model: string | null;
            trim: string | null;
            bodyStyle: string | null;
            driveType: string | null;
            engine: string | null;
            fuelType: string | null;
            transmission: string | null;
            exteriorColor: string | null;
            interiorColor: string | null;
            /** Format: int32 */
            mileage: number | null;
            status: string;
            listPrice: string | null;
            description: string | null;
            aiDescriptionDraft: string | null;
            /** Format: date */
            acquiredAt: string | null;
            /** Format: date */
            availableAt: string | null;
            /** Format: date */
            soldAt: string | null;
            isPublished: boolean;
            location: string | null;
            notes: string | null;
            /** Format: int32 */
            daysInInventory: number | null;
            readiness: components["schemas"]["PublishReadinessDto"];
            allowedTransitions: string[];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        VehicleSummaryDto: {
            /** Format: uuid */
            id: string;
            stockNumber: string;
            vin: string | null;
            /** Format: int32 */
            modelYear: number | null;
            make: string | null;
            model: string | null;
            trim: string | null;
            /** Format: int32 */
            mileage: number | null;
            exteriorColor: string | null;
            status: string;
            listPrice: string | null;
            /** Format: int32 */
            daysInInventory: number | null;
            /** Format: int32 */
            daysToSale: number | null;
            isPublished: boolean;
            /** Format: int32 */
            photoCount: number;
        };
        VerifyMfaRequest: {
            challengeToken: string | null;
            code: string | null;
        };
        VinDecodeDto: {
            vin: string;
            provider: string;
            fromCache: boolean;
            checkDigitValid: boolean;
            /** Format: int32 */
            modelYear: number | null;
            make: string | null;
            model: string | null;
            trim: string | null;
            bodyStyle: string | null;
            driveType: string | null;
            engine: string | null;
            fuelType: string | null;
            transmission: string | null;
            manufacturer: string | null;
            errorText: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    decodeVin: {
        parameters: {
            query?: {
                refresh?: boolean;
            };
            header?: never;
            path: {
                vin: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VinDecodeDto"];
                };
            };
            /** @description Missing, expired, or invalid credentials. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                };
            };
            /** @description The principal lacks the required permission. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                };
            };
            /** @description Not found, or the resource belongs to another tenant. These cases are deliberately indistinguishable: a 403 would confirm the record exists. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Missing, expired, or invalid credentials. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    verifyMfa: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyMfaRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Missing, expired, or invalid credentials. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    confirmMfaEnrolment: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyMfaRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Missing, expired, or invalid credentials. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    redeemRecoveryCode: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RedeemRecoveryCodeRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Missing, expired, or invalid credentials. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    getRecoveryCodeStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecoveryCodeStatusDto"];
                };
            };
            /** @description Missing, expired, or invalid credentials. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                };
            };
            /** @description The principal lacks the required permission. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                };
            };
        };
    };
    regenerateRecoveryCodes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecoveryCodeSetDto"];
                };
            };
            /** @description Missing, expired, or invalid credentials. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    refreshToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair2"];
                };
            };
            /** @description Missing, expired, or invalid credentials. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing, expired, or invalid credentials. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                };
            };
            /** @description The principal lacks the required permission. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                };
            };
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentUserDto"];
                };
            };
            /** @description Missing, expired, or invalid credentials. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                };
            };
            /** @description The principal lacks the required permission. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                };
            };
        };
    };
    listVehicles: {
        parameters: {
            query?: {
                page?: number;
                pageSize?: number;
                sort?: string;
                q?: string;
                status?: string[];
                make?: string;
                model?: string;
                isPublished?: boolean;
                ageDaysMin?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedResultOfVehicleSummaryDto"];
                };
            };
            /** @description Missing, expired, or invalid credentials. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                };
            };
            /** @description The principal lacks the required permission. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                };
            };
        };
    };
    createVehicle: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateVehicleCommand"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VehicleDto"];
                };
            };
            /** @description Missing, expired, or invalid credentials. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                };
            };
            /** @description The principal lacks the required permission. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    getVehicle: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vehicleId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VehicleDto"];
                };
            };
            /** @description Missing, expired, or invalid credentials. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                };
            };
            /** @description The principal lacks the required permission. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                };
            };
            /** @description Not found, or the resource belongs to another tenant. These cases are deliberately indistinguishable: a 403 would confirm the record exists. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                };
            };
        };
    };
    deleteVehicle: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vehicleId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing, expired, or invalid credentials. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                };
            };
            /** @description The principal lacks the required permission. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                };
            };
            /** @description Not found, or the resource belongs to another tenant. These cases are deliberately indistinguishable: a 403 would confirm the record exists. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    changeVehicleStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vehicleId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangeStatusRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VehicleDto"];
                };
            };
            /** @description Missing, expired, or invalid credentials. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                };
            };
            /** @description The principal lacks the required permission. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                };
            };
            /** @description Not found, or the resource belongs to another tenant. These cases are deliberately indistinguishable: a 403 would confirm the record exists. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    changeVehiclePrice: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vehicleId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePriceRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VehicleDto"];
                };
            };
            /** @description Missing, expired, or invalid credentials. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                };
            };
            /** @description The principal lacks the required permission. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                };
            };
            /** @description Not found, or the resource belongs to another tenant. These cases are deliberately indistinguishable: a 403 would confirm the record exists. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    publishVehicle: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vehicleId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VehicleDto"];
                };
            };
            /** @description Missing, expired, or invalid credentials. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                };
            };
            /** @description The principal lacks the required permission. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                };
            };
            /** @description Not found, or the resource belongs to another tenant. These cases are deliberately indistinguishable: a 403 would confirm the record exists. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
}
